### ISSUE TITLE
After using iterator.SeekPrefix, the iterator stop working beyond the current element

### ISSUE THREAD

**Issue by asogor** [hashicorp/go-immutable-radix#7]
```go
func TestSeekPrefix(t *testing.T){
	index := iradix.New()
	index, _ , _ = index.Insert([]byte("aaa"),"aaa")
	index, _ , _ = index.Insert([]byte("bbb"),"bbb")
	index, _ , _ = index.Insert([]byte("ccc"),"ccc")
	index, _ , _ = index.Insert([]byte("ddd"),"ddd")
	index, _ , _ = index.Insert([]byte("eee"),"eee")
	iterator := index.Root().Iterator()
	k,v,got := iterator.Next()
	for got{
		t.Log(k,v)
		k,v,got = iterator.Next()
	}
	iterator.SeekPrefix([]byte("c"))
	k,v,got = iterator.Next()
	for got{
		t.Log("SF: ", k,v)
		k,v,got = iterator.Next()
	}
}
```

**Comment by armon** [comment]
@asogor This is probably just bad documentation, but this is expected behavior. Once you seek to the prefix, only values containing that prefix will be returned (e.g. `c*`). There is only a single key that matches, so that is the only value that you will see.

**Comment by asogor** [comment]
@armon that is fair. What would be an effective way than to do a range scan? Like "b" to "d".

**Comment by armon** [comment]
@asogor Not with the current API unfortunately. But if you wanted to PR a range-based iterator that would be neat!

**Comment by vivekpatani** [comment]
@asogor @armon is there a way to get all the keys in the tree? Tried using the largestPrefix/prefix with an empty key but didn't elicit the correct response. Thanks.
